export const PLANETS = [
    /* - - Sun - - */
    {
        name: "sun",
        displayName: "太阳",
        caption: "黄矮星",
        description: "太阳是我们太阳系的中心，也是地球生命的源泉。太阳核心的温度约为1500万摄氏度（2700万华氏度）。",
        year: "2.3亿地球年",
        day: null,
        radius: 695508,
        meanTemp: 5500,  // 表面（光球层）温度
        timesLarger: 109.2,
        orbitalVelocity: 0,
        orbitObject: null,
        orbitalRadius: 0,
        scaledOrbitalRadius: 0,
        rotationVelocity: 2,
        orbitalInclination: 0,
        axialTilt: 7.25,
        color: '#ffff00',
    },
    /* - - Sun - - */

    /* - - Planets - - */
    {
        name: "mercury",
        displayName: "水星",
        caption: "迅捷行星",
        description: "水星是我们太阳系中最快和最小的行星。在水星表面，太阳看起来比在地球上大3倍。",
        year: "88个地球日",
        day: "59个地球日",
        moons: 0,
        distanceFromSun: 0.4,
        minTemp: -173,
        maxTemp: 427,
        meanTemp: 179,  // 平均温度
        radius: 2439.7,
        timesLarger: 0.38,
        orbitalVelocity: 47.9,
        orbitObject: "sun",
        orbitalRadius: 57909050,
        scaledOrbitalRadius: 24,
        rotationVelocity: 0.003,
        orbitalInclination: 7,
        axialTilt: 0.03,
        color: '#a0522d',
    },
    {
        name: "venus",
        displayName: "金星",
        caption: "晨星",
        description: "金星是我们太阳系中最热的行星。这是由于其厚厚的大气层捕获热量并造成温室效应。",
        year: "225个地球日",
        day: "243个地球日",
        moons: 0,
        distanceFromSun: 0.7,
        meanTemp: 465,  // 表面温度，大气层极厚
        radius: 6051.8,
        timesLarger: 0.9,
        orbitalVelocity: 35.0,
        orbitObject: "sun",
        orbitalRadius: 108200000,
        scaledOrbitalRadius: 31,
        rotationVelocity: 0.003,
        orbitalInclination: 3.4,
        axialTilt: 177,
        color: '#ffd700',
    },
    {
        name: "earth",
        displayName: "地球",
        caption: "蓝色星球",
        description: "地球是太阳系中唯一表面有液态水的行星。大气层让我们人类能够呼吸，同时也保护我们免受陨石的侵害。",
        year: "365.25个地球日",
        day: "23.9小时",
        moons: 1,
        distanceFromSun: 1,
        minTemp: -89,
        maxTemp: 58,
        meanTemp: 15,  // 地表平均温度
        radius: 6371,
        timesLarger: -1,
        orbitalVelocity: 29.8,
        orbitObject: "sun",
        orbitalRadius: 149600000,
        scaledOrbitalRadius: 37,
        rotationVelocity: 0.46,
        orbitalInclination: 0,
        axialTilt: 23.44,
        color: '#4169e1',
    },
    {
        name: "mars",
        displayName: "火星",
        caption: "红色星球",
        description: "火星是我们在地球之外最好的居住候选星球。这是我们唯一派遣探测车登陆的行星。毅力号探测车的火星样本预计将在2033年返回地球。",
        year: "1.88个地球年",
        day: "24.6小时",
        moons: 2,
        distanceFromSun: 1.5,
        minTemp: -125,
        maxTemp: 20,
        meanTemp: -63,  // 平均温度
        radius: 3389.5,
        timesLarger: 0.52,
        orbitalVelocity: 24.1,
        orbitObject: "sun",
        orbitalRadius: 227939366,
        scaledOrbitalRadius: 45,
        rotationVelocity: 0.241,
        orbitalInclination: 1.8,
        axialTilt: 25.19,
        color: '#ff4500',
    },
    {
        name: "jupiter",
        displayName: "木星",
        caption: "巨行星",
        description: "木星是我们太阳系中最大的行星。大红斑是木星的超级风暴，其大小是地球的两倍，已经持续肆虐超过100年。",
        year: "11.86个地球年",
        day: "9.93小时",
        moons: 79,
        distanceFromSun: 5.1,
        meanTemp: -120,  // 云层顶部温度
        radius: 69911,
        timesLarger: 11,
        orbitalVelocity: 24.1,
        orbitObject: "sun",
        orbitalRadius: 778412027,
        scaledOrbitalRadius: 72,
        rotationVelocity: 12.6,
        orbitalInclination: 1.3,
        axialTilt: 3.13,
        color: '#deb887',
    },
    {
        name: "saturn",
        displayName: "土星",
        caption: "环状行星",
        description: "土星不是太阳系中唯一有环的行星，但没有哪个行星的环能比土星的更美。土星总共有7个环。",
        year: "29.45个地球年",
        day: "10.7小时",
        moons: 82,
        distanceFromSun: 9.5,
        meanTemp: -160,  // 云层顶部温度
        radius: 58232,
        timesLarger: 9.1,
        orbitalVelocity: 9.7,
        orbitObject: "sun",
        orbitalRadius: 1433530000,
        scaledOrbitalRadius: 108,
        rotationVelocity: 9.87,
        orbitalInclination: 2.5,
        axialTilt: 26.73,
        color: '#f4a460',
    },
    {
        name: "uranus",
        displayName: "天王星",
        caption: "冰巨星",
        description: "天王星是一颗冰质气态巨行星。它是太阳系中唯一一个侧躺着自转的行星。和金星一样，天王星也是自东向西旋转。",
        year: "84个地球年",
        day: "17小时",
        moons: 27,
        distanceFromSun: 19.8,
        meanTemp: -205,  // 表面温度（基于辐射平衡）
        radius: 25362,
        timesLarger: 4,
        orbitalVelocity: 6.8,
        orbitObject: "sun",
        orbitalRadius: 2870972000,
        scaledOrbitalRadius: 145,
        rotationVelocity: 2.59,
        orbitalInclination: 0.8,
        axialTilt: 82.23,
        color: '#87ceeb',
    },
    {
        name: "neptune",
        displayName: "海王星",
        caption: "大蓝行星",
        description: "海王星是太阳系中唯一一个肉眼看不见的行星。NASA的旅行者2号在1989年飞越海王星，是迄今为止唯一一个近距离访问它的航天器。",
        year: "164个地球年",
        day: "16小时",
        moons: 14,
        distanceFromSun: 30.1,
        meanTemp: -218,  // 表面温度（基于辐射平衡）
        radius: 24622,
        timesLarger: 3.9,
        orbitalVelocity: 5.4,
        orbitObject: "sun",
        orbitalRadius: 4514953000,
        scaledOrbitalRadius: 180,
        rotationVelocity: 2.6,
        orbitalInclination: 1.8,
        axialTilt: 28.32,
        color: '#1e90ff',
    },
    /* - - Sun - - */

    /* - - Moons - - */
    {
        name: "moon",
        displayName: "地球的月球",
        caption: "夜空中最亮的天体",
        description: "地球的月球是太阳系第五大卫星。到目前为止，月球已经接待了24位人类访客和超过105个机器人访客。",
        year: "27天",
        radius: 1737.5,
        timesLarger: 0.27,
        distance: 385000,
        minTemp: -173,
        maxTemp: 127,
        orbitalVelocity: 1.022,
        orbitObject: "earth",
        orbitalRadius: 385000,
        scaledOrbitalRadius: 3,
        rotationVelocity: 0.005,
        orbitalInclination: 5.1,
    },
    {
        name: "io",
        displayName: "木卫一",
        caption: "最具火山活动的卫星",
        description: "木卫一是太阳系中最具火山活动的卫星。它的湖泊是由熔岩组成的。一些火山的威力如此强大，以至于可以用望远镜从地球上看到。",
        year: "42小时",
        radius: 1821.6,
        timesLarger: 0.285,
        distance: 262000,
        meanTemp: -143,
        orbitalVelocity: 17.334,
        orbitObject: "jupiter",
        orbitalRadius: 262000,
        scaledOrbitalRadius: 10,
        rotationVelocity: 0.07,
        orbitalInclination: 0.05,
    },
    {
        name: "europa",
        displayName: "木卫二",
        caption: "可能存在生命的卫星",
        description: "木卫二的地下海洋含有比地球海洋更多的水。它的冰冻表面下可能存在某种形式的生命。",
        year: "85小时",
        radius: 1560.8,
        timesLarger: 0.24,
        distance: 670900,
        minTemp: -220,
        maxTemp: -160,
        orbitalVelocity: 13.743,
        orbitObject: "jupiter",
        orbitalRadius: 670900,
        scaledOrbitalRadius: 13,
        rotationVelocity: 0.03,
        orbitalInclination: 0.47,
    },
    {
        name: "ganymede",
        displayName: "木卫三",
        caption: "太阳系中最大的卫星",
        description: "木卫三是太阳系中最大的卫星。它比水星还大。木卫三有地下海洋和微弱的氧气大气层。它也是唯一一个有自己的磁场的卫星。",
        year: "172小时",
        radius: 2634.1,
        timesLarger: 0.416,
        distance: 1070400,
        minTemp: -180,
        maxTemp: -113,
        orbitalVelocity: 10.880,
        orbitObject: "jupiter",
        orbitalRadius: 1070400,
        scaledOrbitalRadius: 15,
        rotationVelocity: 0.026,
        orbitalInclination: 0.2,
    },
    {
        name: "callisto",
        displayName: "木卫四",
        caption: "最古老的卫星",
        description: "木卫四是太阳系中最古老的卫星。它的表面几乎没有地质活动，但可能有地下海洋。",
        year: "17天",
        radius: 2410.3,
        timesLarger: 0.384,
        distance: 1883000,
        minTemp: -193,
        maxTemp: -108,
        orbitalVelocity: 8.204,
        orbitObject: "jupiter",
        orbitalRadius: 1883000,
        scaledOrbitalRadius: 17.5,
        rotationVelocity: 0.01,
        orbitalInclination: 0.28,
    },
    {
        name: "titan",
        displayName: "土卫六",
        caption: "表面有液体的卫星",
        description: "土卫六是太阳系中唯一一个有云层和浓密大气层的卫星。它的表面也有湖泊和海洋，但它们是由甲烷和乙烷组成的。",
        year: "16天",
        radius: 2574.7,
        timesLarger: 0.4,
        distance: 1221865,
        meanTemp: -179,
        orbitalVelocity: 5.57,
        orbitObject: "saturn",
        orbitalRadius: 1221865,
        scaledOrbitalRadius: 16,
        rotationVelocity: 0.011,
        orbitalInclination: 0.33,
    },
    {
        name: "triton",
        displayName: "海卫一",
        caption: "太阳系中最冷的卫星",
        description: "海卫一是太阳系中最冷的卫星。它也是唯一一个逆行的卫星，也就是说它的公转方向与海王星的自转方向相反。",
        year: "141小时",
        radius: 1353.4,
        timesLarger: 0.21,
        distance: 354759,
        meanTemp: -235,
        orbitalVelocity: 4.39,
        orbitObject: "neptune",
        orbitalRadius: 354759,
        scaledOrbitalRadius: 7,
        rotationVelocity: 0.017,
        orbitalInclination: 156.885,
    },
    /* - - Moons - - */
]